### ISSUE TITLE
New package not used in class

### ISSUE THREAD

**Issue by tonymagr** [quar-tech/mvc-recipe-sharing#2]
We agreed (for now) to check into new NPM packages available to bring new functionality into the deployed project, enhance our development experience, or enhance one or more components of our repo for improved open-source sharing.
I (tonymagr) am the new member on the team (and am excited!), and I will work this issue.

**Comment by maddieeckstrom** [comment]
Tony completed adding nodemailer

**Comment by tonymagr** [comment]
Thanks for completing the issue Maddie.
